config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"

  get "login" => "sessions#new", as: :login
  post "auth" => "sessions#create", as: :auth
  post "logout" => "sessions#destroy", as: :logout

  resources :bands
  resources :venues
  resources :search, only: [:index]
  resources :shows do
    member do
      post :publish
    end
  end
  resources :videos

  scope :admin do
    get "/" => "home#admin", as: :admin
    get "/features/set" => "features#set", as: :set_feature
    resources :features, only: [:edit, :update]
    resources :supporters, only: [:create, :update, :destroy]
  end
end

app/models/video.rb
class Video < ApplicationRecord
  include PgSearch::Model

  belongs_to :band
  belongs_to :show
  has_one :venue, through: :show

  pg_search_scope :search,
    against: [:name],
    associated_against: {
      band: :name,
      show: :name,
      venue: :name
    }

  multisearchable against: [:search_keywords], if: :published?

  after_create :check_show_status!

  enum :status, draft: 0, ready: 5, published: 10

  validates :show, :band, :name, :url, presence: true
  validates :url,
    format: {
      with: /\Ahttps:\/\/(?:www.)?youtube.com\/watch\?v=[A-Za-z0-9_\-]+\z/,
      message: "is invalid. Make sure you are using a FULL youtube link: \n\"https://www.youtube.com/watch?v=RKjk0ECXjiQ\""
    }

  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end

  def feature
    Feature.find_by(target_id: id)
  end

  def feature?
    feature.present?
  end

  def display_name
    "#{name} by #{band.name} at #{venue.name}"
  end

  def display_image
    band.image
  end

  def search_keywords
    "#{show.name} #{name} #{band.name} #{venue.name}"
  end

  private

  def check_show_status!
    show.ready! if show.ready_to_publish?
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :set_video_scope, only: [:index, :show]
  before_action :require_login, only: [:new, :edit, :create, :update, :destroy]

  def index
    @videos = @scoped_videos.order(created_at: :desc)

    # URL Parameter Filters
    @videos = @videos.where(band_id: params[:band_id]) if params[:band_id]
    @videos = @videos.where(show_id: params[:show_id]) if params[:show_id]
    @videos = @videos.joins(:show).where(shows: { venue_id: params[:venue_id]}) if params[:venue_id]

    @videos = @videos.page(params[:page])

    @hide_band = params[:band_id].present?
    @hide_venue = params[:venue_id].present? || params[:show_id].present?
  end

  def show
    @video = @scoped_videos.find(params[:id])
    @videos = @video.band.videos - [@video]
    @shows = @video.band.shows.order(date: :desc) - [@video.show]
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to @video.show, notice: 'Video was added successfully!'
    else
      render :new
    end
  end

  def update
    if @video.update(video_params)
      redirect_to @video, notice: 'Video was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_url, notice: 'Video was successfully destroyed.'
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def set_video_scope
    @scoped_videos ||= current_user ? Video.all : Video.published
    @scoped_videos = @scoped_videos.search(params[:q]) if params[:q]
    @scoped_videos
  end

  def video_params
    params.require(:video).permit(
      :band_id,
      :show_id,
      :name,
      :url,
      :status
    )
  end
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</p>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :show_id %>
    <%= form.select :show_id, options_for_select(Show.options_for_select, params[:show_id] || @video.show&.id), { include_blank: "Select a show" }, id: :video_show_id, class: "form-control form-control-lg" %>
  </div>

  <div class="mb-4">
    <%= form.label :band_id %>
    <%= form.select :band_id, options_from_collection_for_select(Band.all.order(:name), "id", "name", params[:band_id] || @video.band&.id), { include_blank: "Select a band" }, id: :video_band_id, class: "form-control form-control-lg" %>
  </div>

  <div class="mb-4">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, id: :video_name, class: "form-control form-control-lg" %>
    <p class="form-text">
      This will typically be <em>Song Name</em> or <em>Full Set</em>, but, you know, whatevs.
    </p>
  </div>

  <% if current_user.admin? %>
    <div class="mb-4">
      <%= form.label :status %>
      <%=
        form.select :status, Video.statuses.keys.map { |w| [w.humanize, w] }, {},
        class: "form-control form-control-lg"
      %>
      <p class="form-text">This is an admin-only field. If you can see this, you are an admin.</p>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :url, "Video URL" %>
    <%= form.text_field :url, placeholder: "https://www.youtube.com/watch?v=314159", id: :video_url, class: "form-control form-control-lg" %>
  </div>

  <div class="d-grid">
    <%= form.submit "Save", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/videos/_list.html.erb
<div class="d-flex flex-wrap justify-content-around">
  <% videos.each do |video| %>
    <div class="p-2" style="width: 400px">
      <div class="video-container">
        <iframe src="//youtube.com/embed/<%= video.url.split("=").last %>" frameborder="0"  title="YouTube Video" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>

      <p>
        <em><%= link_to video.name, video_path(video) %></em>

        <% if include_band %>
          by <%= link_to video.band.name, video.band %>
        <% end %>

        <% if include_venue %>
          at <%= link_to video.show.venue.name, video.show.venue %>
        <% end %>

        <%= video.show.date.strftime("on %B #{video.show.date.day.ordinalize}, %Y") if include_date %>
      </p>

      <%= simple_format(video.feature.caption) if video.feature && controller_name == 'home' %>
    </div>
  <% end %>
</div>

app/views/videos/edit.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2">
    <%= render "shared/delete_button", object: @video %>
    <h1>Edit Video</h1>
    <%= render 'form', video: @video %>
  </div>
</div>

app/views/videos/index.html.erb
<%= render "shared/social_meta", object: "Videos" %>

<div id="videos">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="text-start">Videos</h1>
    </div>
    <div class="col-sm-4">
      <%= render "shared/search_form", path: videos_path %>
    </div>
  </div>

  <%= search_filters(params) %>

  <%= query_result_details(params[:q], @videos.size) %>

  <table class="table table-striped videos-list">
    <thead>
      <tr>
        <th>Name</th>

        <% unless @hide_band %>
          <th>Band</th>
        <% end %>

        <% unless @hide_venue %>
          <th>Venue</th>
        <% end %>

        <th>Date</th>
      </tr>
    </thead>

    <tbody>
      <% @videos.order(created_at: :desc).each do |video| %>
        <tr>
          <td><%= link_to video.name, video %></td>

          <% unless @hide_band %>
            <td><%= link_to video.band.name, video.band %></td>
          <% end %>

          <% unless @hide_venue %>
            <td><%= link_to video.venue.name, video.venue %></td>
          <% end %>

          <td>
            <span class="d-none d-md-table-cell">
              <%= link_to video.show.date.strftime("%B #{video.show.date.day.ordinalize}, %Y"), video.show %>
            </span>
            <span class="d-sm-table-cell d-md-none">
              <%= link_to video.show.date.strftime("%D"), video.show %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center mt-5">
    <%= will_paginate @videos %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2">
    <h1>New Video</h1>

    <% if params[:band_id].nil? && params[:show_id].nil? %>
      <blockquote>
        <p><strong>PRO-TIP!</strong></p>
        <p>It's <strong>much</strong> easier and more reliable to add a video from an individual show page. Pick a show <strong><%= link_to "from here", shows_path %></strong> and then next to each band name you'll see an "add a video" link that will pre-populate this form with the correct show and band.</p>
      </blockquote>
    <% end %>

    <%= render "form", video: @video %>
  </div>
</div>

app/views/videos/show.html.erb
<%= render "shared/social_meta", object: @video %>
<%= render "shared/admin_links", object: @video %>

<div id="video">
  <div class="row mb-5">
    <div class="col-sm-10 offset-sm-1">
      <div class="video-container">
        <iframe src="//youtube.com/embed/<%= @video.url.split("=").last %>" frameborder="0" title="YouTube Video" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>

      <h3 class="text-center">
        <em><%= @video.name %></em> by <%= link_to @video.band.name, @video.band %><br>
        <small>
          at <%= link_to @video.venue.name, @video.venue %>
          on <%= link_to @video.show.date.strftime("%B #{@video.show.date.day.ordinalize}, %Y"), @video.show %>
        </small>
      </h3>
    </div>
  </div>

  <% if @videos.size >= 1 %>
    <h3>Other videos by <em><%= @video.band.name %></em></h3>

    <%=
      render partial: "videos/list", locals: {
        videos: @videos.sample(3),
        include_band:  true,
        include_venue: true,
        include_date:  true
      }
    %>
  <% end %>

  <% if @videos.size > 3 %>
    <%= link_to "All videos by <em>#{@video.band.name}</em>".html_safe, videos_url(band_id: @video.band.id), class: 'btn btn-md btn-info btn-center' %>
  <% end %>

  <hr>

  <% if @shows.any? %>
    <h3>Shows with <em><%= @video.band.name %></em></h3>

    <%=
      render partial: "shows/list", locals: {
        shows: @shows,
        include_venue: true,
        include_headers: false
      }
    %>
  <% end %>
</div>