config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"

  get "login" => "sessions#new", as: :login
  post "auth" => "sessions#create", as: :auth
  post "logout" => "sessions#destroy", as: :logout

  resources :bands
  resources :venues
  resources :search, only: [:index]
  resources :shows do
    member do
      post :publish
    end
  end
  resources :videos

  scope :admin do
    get "/" => "home#admin", as: :admin
    get "/features/set" => "features#set", as: :set_feature
    resources :features, only: [:edit, :update]
    resources :supporters, only: [:create, :update, :destroy]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login, only: [:admin]

  def index
    @main_feature = Feature.find_by(name: 'video-1')
    @main_video = @main_feature.video
    @other_features = Feature.where(name: ['video-2', 'video-3', 'video-4'])
    @recent_shows = Show.order(created_at: :desc).limit(3)
    @recent_bands = Band.order(created_at: :desc).limit(3)
    @recent_videos = Video.order(created_at: :desc).limit(3)
    @supporters = Supporter.all.order(:name).pluck(:name)
  end

  def admin
    @main_feature = Feature.find_by(name: 'video-1')
    @other_features = Feature.where(name: ['video-2', 'video-3', 'video-4'])
    @ready_to_publish_shows = Show.ready
    @shows_in_draft = Show.draft.order(:created_at).limit(10)

    @supporters = Supporter.all.order(:name)

    if params[:supporter_id].present?
      @supporter = Supporter.find(params[:supporter_id])
      @supporter_name_label = "Edit Supporter - #{helpers.link_to 'Cancel', admin_path}".html_safe
    else
      @supporter = Supporter.new
      @supporter_name_label = "Add New Supporter"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<%= render "shared/social_meta", object: "Admin" %>

<div id="admin">
  <div class="pull-right">
    <%= link_to "New Band", new_band_path, class: "btn btn-info" %>
    <%= link_to "New Venue", new_venue_path, class: "btn btn-info" %>
    <%= link_to "New Show", new_show_path, class: "btn btn-info" %>
    <%= link_to "New Video", new_video_path, class: "btn btn-info" %>
  </div>

  <h1 class="text-start">Admin</h1>

  <div class="row">
    <div class="col-sm-4">
      <h3>Publishable Shows</h3>
      <p class="form-text">A show must have a venue, at least one band, and at least one video per band in order to publish it. Publishing a show will automatically publish everything in the show as well: venue, bands, and videos.</p>
      <% if @ready_to_publish_shows.any? %>
        <table class="table table-striped">
          <% @ready_to_publish_shows.each do |show| %>
            <tr>
              <td><%= link_to show.display_name, show %></td>
              <td>
                <%=
                  link_to "Publish!",
                  publish_show_path(show),
                  method: :post,
                  data: { confirm: "Are you sure you want to publish this show and all its content?" },
                  class: "btn btn-xs btn-success",
                  disabled: !current_user.admin?
                %>
              </td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <table class="table table-striped">
          <tr>
            <td>You have no publishable shows. Check your drafts!</td>
          </tr>
        </table>
      <% end %>
      <p class="form-text">The <a href="#" class="btn btn-sm btn-success" <%= "disabled" if !current_user.admin? %>>Publish!</a> buttons can only be clicked by admins.</p>
    </div>

    <div class="col-sm-4">
      <h3>Draft Shows</h3>
      <p class="form-text">Most likely, one of the bands doesn"t have any videos yet. This list will never have more 10 items (sorted oldest first). When a show moves over to Publishable, another draft will appear on this list.</p>
      <% if @shows_in_draft.any? %>
        <table class="table table-striped">
          <% @shows_in_draft.each do |show| %>
            <tr>
              <td><%= link_to show.display_name, show %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <table class="table table-striped">
          <tr>
            <td>You have no draft shows. Check your publishable!</td>
          </tr>
        </table>
      <% end %>
    </div>

    <div class="col-sm-4">
      <h3>Supporters</h3>
      <p class="form-text">Add a new supporter with the form below. Click an existing supporter's name to edit in the form below. Click the <%= icon("times") %> to remove a support from the list.</p>

      <%= form_with(model: @supporter, local: true) do |form| %>
        <div class="mb-4">
          <%= form.label :name, @supporter_name_label %>
          <div class="input-group">
            <%= form.text_field :name, placeholder: "Supporter name", id: :supporter_name, class: "form-control form-control-md" %>

            <div class="input-group-text">
              <button type="submit" class="btn btn-xs btn-primary">
                SAVE
              </button>
            </div>
          </div>
        </div>
      <% end %>

      <ul class="list-inline">
        <% @supporters.each do |supporter| %>
          <li class="list-inline-item fs-6">
            <%= link_to supporter.name, admin_path(supporter_id: supporter.id) %>
            <%=
              link_to icon("times"),
              supporter_path(supporter),
              data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to remove #{supporter.name} from the supporters list?"
              }
            %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="home">
  <div class="row">
    <h1>Welcome to Blue Heron Video</h1>

    <div class="col-sm-5 offset-sm-1">
      <p class="lead text-start">Blue Heron Video is trying to film all bands in, and touring through, Portland. Since 2014, a very good chunk has been documented with consent to post and at no cost to the bands. With over 2200 bands filmed, often multiple times from different shows and venues, it is a wide ranging and impressive array of the music scene in Portland.</p>
      <p class="lead text-start"><%= link_to 'Subscribe to the channel', 'https://www.youtube.com/blueheronvideo', target: '_blank' %>, start watching, and help support the progress!!</p>
    </div>

    <div class="col-sm-5">
      <div class="video-container">
        <iframe src="//youtube.com/embed/bRK9PPBueuE" frameborder="0" title="YouTube Video" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
    </div>
  </div>

  <hr>

  <div class="videos">
    <h2>Selected Videos</h2>
    <%=
      render partial: "videos/list", locals: {
        videos: Video.all.sample(3),
        include_band: true,
        include_venue: true,
        include_date: true
      }
    %>
  </div>

  <hr>

  <div class="row mb-5">
    <h2>Selected Bands</h2>
    <div class="d-flex flex-wrap justify-content-around">
      <% Band.all.sample(3).each do |band| %>
        <div class="p-2" style="width: 400px">
          <%= link_to band do %>
            <%= image_tag(image_url_for(band), class: 'img-fluid') %>
            <h3><%= band.name %></h3>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row support">
    <h2>Support</h2>

    <div class="col-sm-8 offset-sm-2">
      <p class="lead">If you appreciate the work being done here, then please consider becoming a patron, ordering a t-shirt, and/or simply sending along some digital cash! Every bit helps.</p>
    </div>

    <div class="col-sm-4">
      <ul class="list-unstyled">
        <li>
          <%= link_to "https://venmo.com/blueheronvideo", target: "_blank" do %>
            <%= image_tag "venmo.png", class: "img-fluid" %>
          <% end %>
        </li>

        <li>
          <%= link_to "https://www.patreon.com/bePatron?u=14353144", target: "_blank" do %>
            <%= image_tag "patreon.png", class: "img-fluid" %>
          <% end %>
        </li>

        <li>
          <%= link_to "https://ko-fi.com/blueheronvideo", target: "_blank" do %>
            <%= image_tag "ko-fi.png", class: "img-fluid" %>
          <% end %>
        </li>

        <li>
          <%= link_to "https://paypal.me/blueheronvideo", target: "_blank" do %>
            <%= image_tag "paypal.png", class: "img-fluid" %>
          <% end %>
        </li>
      </ul>
    </div>

    <div class="col-sm-4">
      <%= image_tag "tshirt.png", class: "img-fluid" %>
      <p class="small">T-shirts are $25 (including shipping)</p>
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="643ECZX3DHWLA">
        <input type="hidden" name="on0" value="Sizes">
        <select name="os0">
          <option value="Women's M">Women's M</option>
          <option value="Women's L">Women's L</option>
          <option value="Men's S">Men's S</option>
          <option value="Men's M">Men's M</option>
          <option value="Men's L">Men's L</option>
          <option value="Men's XL">Men's XL</option>
        </select>
        <button type="submit" class="btn btn-xs btn-success">
          PAY WITH PAYPAL
        </button>
      </form>
    </div>

    <div class="col-sm-4">
      <%= image_tag "sticker.jpg", class: "img-fluid" %>
      <p class="small">
        Free sticker (3" x 2.5") included<br>
        with each t-shirt order
      </p>
    </div>
  </div>

  <div class="row featured-video">
    <div class="col-md-10 offset-md-1">
      <h2>Featured Video</h2>

      <div class="video-container">
        <iframe src="//youtube.com/embed/<%= @main_video.url.split("=").last %>" frameborder="0" title="YouTube Video" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>

      <h3>
        <%= link_to @main_video.name, @main_video %>
        by <%= link_to @main_video.band.name, @main_video.band %>
        at <%= link_to @main_video.show.venue.name, @main_video.show.venue %>
        on <%= link_to @main_video.show.date.strftime("%B #{@main_video.show.date.day.ordinalize}, %Y"), @main_video.show %>
      </h3>

      <p><%= @main_feature.caption %></p>

      <% if current_user && controller_name == "home" %>
        <span class="btn-center">
          <%= link_to "edit feature", edit_feature_path(@main_feature, video_id: @main_video.id), class: "btn btn-xs btn-primary" %>
        </span>
      <% end %>
    </div>
  </div>

  <div class="row shows">
    <h2>Selected Shows</h2>
    <% Show.all.sample(3).each do |show| %>
      <div class="show col-sm-4">
        <%= link_to show do %>
          <h3><%= show.venue.name %></h3>
          <p><%= show.date.strftime("%B #{show.date.day.ordinalize}, %Y") %></p>
          <ul class="list-unstyled">
            <% show.bands.each do |band| %>
              <li><%= band.name %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="supporters">
    <h2>Thank You, Supporters!</h2>
    <ul class="list-inline">
      <% @supporters.each do |name| %>
        <li class="list-inline-item"><%= name %></li>
      <% end %>
    </ul>
  </div>
</div>