config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"

  get "login" => "sessions#new", as: :login
  post "auth" => "sessions#create", as: :auth
  post "logout" => "sessions#destroy", as: :logout

  resources :bands
  resources :venues
  resources :search, only: [:index]
  resources :shows do
    member do
      post :publish
    end
  end
  resources :videos

  scope :admin do
    get "/" => "home#admin", as: :admin
    get "/features/set" => "features#set", as: :set_feature
    resources :features, only: [:edit, :update]
    resources :supporters, only: [:create, :update, :destroy]
  end
end

app/models/show.rb
class Show < ApplicationRecord
  include PgSearch::Model

  belongs_to :venue
  has_many :videos
  has_and_belongs_to_many :bands

  pg_search_scope :search,
    against: [:name, :notes],
    associated_against: {
      bands: :name,
      venue: :name
    }

  multisearchable against: [:search_keywords], if: :published?

  validates :venue, :bands, presence: true

  enum :status, draft: 0, ready: 5, published: 10

  def self.options_for_select
    options = []

    all.each do |show|
      options << ["#{show.display_name} at #{show.venue.name}", show.id]
    end

    options
  end

  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end

  def display_name
    name? ? name : bands.map(&:name).sort.join(", ")
  end

  def display_image
    venue.image
  end

  # do all of the bands in the show all have at least one video
  def ready_to_publish?
    bands.pluck(:id).sort == videos.pluck(:band_id).uniq.sort
  end

  def search_keywords
    "#{name} #{bands.map(&:name).sort.join(" ")} #{venue.name}"
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :publish, :destroy]
  before_action :set_show_scope, only: [:index, :show]
  before_action :require_login, only: [:new, :edit, :create, :update, :publish, :destroy]

  def index
    @shows = @scoped_shows.order(date: :desc)

    # URL Parameter Filters
    @shows = @shows.where(venue_id: params[:venue_id]) if params[:venue_id]
    @shows = @shows.where(band_id: params[:band_id]) if params[:band_id]

    @shows = @shows.page(params[:page])
  end

  def show
    @show  = @scoped_shows.find(params[:id])
    @bands = @show.bands.order(:name)
    @videos = @show.videos.order(:name)

    if @bands.size < 3
      @flex_container_adjustment = "style=\"justify-content: flex-start\"".html_safe
      @flex_item_adjustment = "style=\"margin-right: 20px\"".html_safe
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @show = Show.new
  end

  def edit
  end

  def create
    @show = Show.new(show_params)

    if @show.save
      redirect_to @show, notice: 'Show was successfully created.'
    else
      render :new
    end
  end

  def update
    if @show.update(show_params)
      redirect_to @show, notice: 'Show was successfully updated.'
    else
      render :edit
    end
  end

  def publish
    PublishShow.call(@show)
    redirect_back(fallback_location: admin_path)
  end

  def destroy
    @show.destroy
    redirect_to shows_url, notice: 'Show was successfully destroyed.'
  end

  private

  def set_show
    @show = Show.find(params[:id])
  end

  def set_show_scope
    @scoped_shows = current_user ? Show.all : Show.published
    @scoped_shows = @scoped_shows.search(params[:q]) if params[:q]
    @scoped_shows
  end

  def show_params
    params.require(:show).permit(
      :name,
      :date,
      :notes,
      :venue_id,
      :status,
      band_ids: []
    )
  end
end

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</p>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :venue_id %>
    <%= form.select :venue_id, options_from_collection_for_select(Venue.all.order(:name), "id", "name", @show.venue&.id), { include_blank: "Select a Venue" }, id: :show_venue_id, class: "form-control form-control-lg" %>
  </div>

  <div class="mb-4">
    <%= form.label :date %><br>
    <%= form.date_select :date, { order: [:day, :month, :year], start_year: 10.years.ago.year, end_year: Time.now.year }, { class: "form-control form-control-lg", style: "width: auto; display: inline" } %>
  </div>

  <% if current_user.admin? %>
    <div class="mb-4">
      <%= form.label :status %>
      <%=
        form.select :status, Show.statuses.keys.map { |w| [w.humanize, w] }, {},
        class: "form-control form-control-lg"
      %>
      <p class="form-text">This is an admin-only field. If you can see this, you are an admin.</p>
    </div>
  <% end %>

  <div class="mb-4">
    <%= label_tag "Bands" %>
    <ul class="list-unstyled">
      <% Band.all.order(:name).each do |band| %>
        <li class="fs-6">
          <%= check_box_tag "show[band_ids][]", band.id, @show.bands.include?(band), id: band.name.parameterize %>
          <%= label_tag band.name.parameterize, band.name %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="mb-4">
    <%= form.label :name, "Name (optional)" %>
    <%= form.text_field :name, id: :show_name, class: "form-control form-control-lg" %>
    <p class="form-text">
      The show name is usually only included for festivals and such as, like <em>Ceremony of Sludge 2017 First Night</em>. If this is left blank, the show will be named "<em>Band1, Band2... at Venue</em>".
    </p>
  </div>

  <div class="mb-4">
    <%= form.label :notes, "Notes (optional)" %>
    <%= form.text_area :notes, id: :show_notes, class: "form-control form-control-lg" %>
  </div>

  <div class="d-grid">
    <%= form.submit "Save", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/shows/_list.html.erb
<table class="table table-striped shows-list">
  <thead>
    <tr>
      <% if include_headers %>
        <th>Name</th>
      <% end %>

      <% if include_headers %>
        <% if include_venue %>
          <th>
            <span class="d-none d-md-table-cell">
              Venue
            </span>
          </th>
        <% end %>
      <% end %>

      <% if include_headers %>
        <th>Date</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% shows.each do |show| %>
      <tr>
        <td><%= link_to show.display_name, show %></td>

        <% if include_venue %>
          <td>
            <span class="d-none d-md-table-cell">
              <%= link_to show.venue.name, show.venue %>
            </span>
          </td>
        <% end %>

        <td>
          <span class="d-none d-md-table-cell">
            <%= link_to show.date.strftime("%B #{show.date.day.ordinalize}, %Y"), show %>
          </span>
          <span class="d-sm-table-cell d-md-none">
            <%= link_to show.date.strftime("%D"), show %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shows/edit.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2">
    <%= render "shared/delete_button", object: @show %>
    <h1>Edit Show</h1>
    <%= render 'form', show: @show %>
  </div>
</div>

app/views/shows/index.html.erb
<%= render "shared/social_meta", object: "Shows" %>

<div id="shows">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="text-start">Shows</h1>
    </div>
    <div class="col-sm-4">
      <%= render "shared/search_form", path: shows_path %>
    </div>
  </div>

  <%= search_filters(params) %>

  <%= query_result_details(params[:q], @shows.size) %>

  <%=
    render partial: "shows/list", locals: {
      shows: @shows,
      include_venue: true,
      include_headers: true
    }
  %>

  <div class="d-flex justify-content-center mt-5">
    <%= will_paginate @shows %>
  </div>
</div>

app/views/shows/new.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2">
    <h1>New Show</h1>
    <%= render 'form', show: @show %>
  </div>
</div>

app/views/shows/show.html.erb
<%= render "shared/social_meta", object: @show %>
<%= render "shared/admin_links", object: @show %>

<div id="show">
  <div class="row">
    <div class="col-sm-6 col-md-9">
      <h1><%= @show.display_name %></h1>
    </div>
    <div class="col-sm-6 col-md-3">
      <%= image_tag(image_url_for(@show.venue), class: "img-fluid") %>
      <p class="help-block text-center">
        <%= link_to @show.venue.name, @show.venue %><br>
        <%= @show.date.strftime("%B #{@show.date.day.ordinalize}, %Y") %>
      </p>
    </div>
  </div>

  <h3>Bands</h3>

  <div class="d-flex flew-wrap justify-content-start">
    <% @bands.each do |band| %>
      <div class="p-2" style="width: 400px">
        <%= link_to image_tag(image_url_for(band), class: "img-fluid"), band %>
        <p class="text-center">
          <%= link_to band.name, band %>
          <% if current_user %>
            <br><%= link_to "add video", new_video_path(show_id: @show.id, band_id: band.id), class: "btn btn-xs btn-success" %>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>

  <h3>Videos</h3>

  <%=
    render partial: "videos/list", locals: {
      videos: @videos.sample(6),
      include_band: true,
      include_venue: true,
      include_date: true
    }
  %>

  <% if @videos.size > 6 %>
    <%= link_to "Click here for all videos from this show", videos_url(show_id: @show.id), class: "btn btn-md btn-info btn-center" %>
  <% end %>

  <% if @show.notes? %>
    <hr>

    <h3>Notes</h3>

    <%= simple_format(@show.notes) %>
  <% end %>
</div>