config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"

  get "login" => "sessions#new", as: :login
  post "auth" => "sessions#create", as: :auth
  post "logout" => "sessions#destroy", as: :logout

  resources :bands
  resources :venues
  resources :search, only: [:index]
  resources :shows do
    member do
      post :publish
    end
  end
  resources :videos

  scope :admin do
    get "/" => "home#admin", as: :admin
    get "/features/set" => "features#set", as: :set_feature
    resources :features, only: [:edit, :update]
    resources :supporters, only: [:create, :update, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blue Heron Video" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nanum+Myeongjo:700&display=swap">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark mb-4 sticky-top bg-blueheron">
      <div class="container">
        <a class="navbar-brand" href="/">blueheron.video</a>
        <ul class="nav-list d-flex list-unstyled p-0 m-0 gap-4">
          <li><%= link_to icon('search'), search_index_path, class: "link-light text-decoration-none" %></li>
          <li><%= link_to "Bands", bands_path, class: "link-light text-decoration-none" %></li>
          <li><%= link_to "Venues", venues_path, class: "link-light text-decoration-none" %></li>
          <li><%= link_to "Shows", shows_path, class: "link-light text-decoration-none" %></li>
          <% if current_user %>
            <li><%= link_to "Admin", admin_path, class: "link-light text-decoration-none" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= notice %>
            </div>
          </div>
        </div>
      <% end %>

      <%= yield %>

      <div id="footer" class="row">
        <div class="col-sm-12">
          <p>Blue Heron Video | Shelby Kray | <a href="mailto:blueheronvideo@gmail.com">Email</a></p>
          <p>Site design & build by <a href="https://merner.co" target="_blank">merner.co</a></p>
          <p>
            <% if current_user %>
              <%= link_to "Logout", logout_path, data: { turbo_method: :post, turbo_confirm: "Are you sure you want to logout?" } %>
            <% else %>
              <%= link_to "Login", login_path %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</html>